# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-11 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0002_auto_20190811_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('star', models.BooleanField(default=False)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='taskList',
        ),
    ]
